### ISSUE TITLE
Modelling pub/sub

### ISSUE THREAD

**Issue by appedemic** [cjus/umf#2]
I can image a few use-cases where the "to" field is not know or not important and can be best described with `{"to": "whom it may concern"}`. For example, a service sending reporting information or heartbeats.

What would be the best way to model such a use-case? I was thinking to approach this case from a router point-of-view, saying that in those cases the _to_ is some sort of pub/sub system or a message bus (`{"to": "service:pubsub/heartbeat"}` or `{"to": "service:bus/public"}`)

When such a service is forwarding messages, would you recommend modifying the incoming messages or creating new derivative messages? 

For example, service _a_ sends periodic heartbeat messages and some service _b_ is interested in them at some point. An intermediate service _pubsub_ is used to connect them. So _a_ publishes a message in the form of `{"mid": "a-1", "to": "pubsub/heartbeat", from: "a", "type": "heartbeat"}`.

Now at some point _b_ will subscribe on the heartbeat messages. So: 
```
{
  "mid": "b-1", 
  "to": "pubsub/heartbeat", 
  "from": "b", 
  "type": "subscribe", 
  "body": {
    "topic": "a"
  }
}
```

_pubsub_ will send a confirmation message back to _b_: 
```
{
  "mid":"pubsub-1", 
  "rmid":"b-1", 
  "to": "b",
  "from": "pubsub", 
  "type": "subscription"
}
```

So far, so good. Now it's time for the real question :). How would _pubsub_ forward the messages? Would it modify the original message so it becomes:
```
{
  "mid": "a-1",
  "to": "b",
  "via" "pubsub/heartbeat",
  "type": "heartbeat"
}
```
(this feels dirty, reusing mid, which should be unique for a single message)

Or would _pubsub_ generate all new messages, refering the original message?
```
{
  "mid": "pubsub-2",
  "rmid": "a-1",
  "from": "a",
  "to": "b",
  "via": "pubsub/heartbeat",
  "type": "heartbeat"
}
```

Or would it be better to use the for field here, since _b_ expects messages from _pubsub_, and _pubsub_ is sending messages on behalf of _a_?
```
{
  "mid": "pubsub-2",
  "rmid": "a-1",
  "from": "pubsub/heartbeat",
  "to": "b",
  "for": "a",
  "type": "heartbeat"
}
```

**Comment by cjus** [comment]
The `to` field is only really needed for routing but can be anything your application needs. The key here is to consider a day when your requirements might expand to routing. 

When forwarding messages I would recommend using the `via` field and keeping the `to` field intact. 

Whether you change an `mid` is up to you and your system requirements. Ideally an `mid` should uniquely identify a message **body**. At some point, based on application requirements it might be best to add what you need inside of the body object field because of UMF limitations. One example would be the need to track the routes that a message travels through. On each hop, an array inside of body would might a router name/path appended to keep track of traversals.
